version: 2.1
executors:
  exectr:
    docker:
      - image: lonewolfakela/cmake-gcc-compilation:1.3
jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE="~/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
            make
            cd ..
            mkdir build_asan
            cd build_asan
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFOXLOX_USE_MIMALLOC=OFF -DFOXLOX_ENABLE_ASAN=ON -DCMAKE_TOOLCHAIN_FILE="~/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
            make
      - persist_to_workspace:
          root: .
          paths: 
            - build
            - build_asan
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build
            ./tests/tests --gtest_output=xml:~/test_results/report.xml
            cd ../build_asan
            ./tests/tests --gtest_output=xml:~/test_results/report_asan.xml
      - store_test_results:
          path: ~/test_results
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
